version: '3'

services:
  pg-database:
    image: "postgres:11"
    container_name: pg-database
    volumes:
      - gorev3-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: geziajanda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

  backend:
    build: ./backend
    container_name: backend
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    environment:
      - DB_SERVER=pg-database
    ports:
      - "8080:8080"
    links:
      - pg-database

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:80"
    links:
      - backend

volumes:
  gorev3-data: