# Generated by Django 3.0.4 on 2020-03-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tip_date',
            new_name='trip_date',
        ),
    ]
