# Generated by Django 3.0.4 on 2020-03-25 13:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0002_auto_20200323_1355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Trip',
        ),
    ]
