# Generated by Django 3.0.4 on 2020-03-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20200325_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='title',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
    ]
