# Generated by Django 3.0.4 on 2020-04-03 21:11

from django.db import migrations, models
import trips.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_auto_20200403_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.FileField(null=True, upload_to=trips.models.upload_path),
        ),
    ]
