# Generated by Django 3.0.4 on 2020-04-03 21:31

from django.db import migrations, models
import trips.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_auto_20200404_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(null=True, upload_to=trips.models.upload_path),
        ),
    ]
