# Generated by Django 3.0.4 on 2020-04-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_auto_20200404_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='image',
        ),
    ]
